# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Dragonfire

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install requests
        winget install --id Git.Git -e --source winget
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        git clone --depth 1 https://github.com/dragonfireclient/dragonfireclient
        cd dragonfireclient
        git clone --branch 1.9.0mt7 --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt
        vcpkg install zlib zstd curl[winssl] openal-soft libvorbis libogg libjpeg-turbo sqlite3 freetype luajit gmp jsoncpp opengl-registry --triplet x64-windows
        cd..
        py download.py "https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-windows-x86_64.zip" cmake.zip
        py download.py "https://aka.ms/vs/17/release/vs_buildtools.exe" installer.exe
        installer.exe --quiet
        tar -xf cmake.zip
        "cmake-3.28.1-windows-x86_64\bin\cmake.exe" . -G"Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=.vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_GETTEXT=OFF -DENABLE_CURSES=OFF
        "cmake-3.28.1-windows-x86_64\bin\cmake.exe" --build . --config Release
        dir
    
